name: CI

on:
  pull_request:
    paths-ignore:
      - 'microsite/**'
jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v2
        with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
        # This is important to fetch the changes to the previous commit
        fetch-depth: 0

      - name: fetch branch master
        run: git fetch origin master

      - name: yarn install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      # End of yarn setup        

      - name: Prettify docs
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --config docs/prettier.config.js --write docs/**/*.md 
          same_commit: true  
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}  