name: CI

on:
  pull_request:
    paths-ignore:
      - 'microsite/**'
jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v2
      - name: fetch branch master
        run: git fetch origin master