name: Prettier Markdown

on:
  push:
    branches: [master]
    paths:
    - 'docs/**'

jobs:
  pretty:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm install -g yarn    
    - run: yarn install
    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --config docs/prettier.config.js --write docs/**/*.md 
      env:
        GITHUB_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
