name: Prettier Markdown

on:
  pull_request:  
    paths:
    - 'docs/**'

jobs:
  pretty:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - name: Use Node.js
      uses: actions/setup-node@v2
    - run: yarn --frozen-lockfile
    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        prettier_options: --config docs/prettier.config.js --write docs/**/*.md 
      env:
        GITHUB_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
